apiVersion: v2
name: pagopa-mbd
description: Microservice that permits to handle Digital Stamps in pagoPA platform
type: application
version: 0.37.0
appVersion: 0.2.10
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
  - name: cron-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: runflussi-cron
  - name: cron-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: renametransfer-cron
  - name: cron-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: getelabricevute-cron
